### ISSUE TITLE
DaumpostcodeEmbed 메소드 사용시 Document.write() 가 문제가 됩니다. 

### ISSUE THREAD

**Issue by Luceta** [kmsbernard/react-daum-postcode#53]
현 리액트 프로젝트에서 documpostcodeEmbed를 사용해서 주소 검색을 보여주고 있습니다.
유저가 버튼을 클릭시 embed가 띄워지는데, 그 상황에서 매번 콘솔에서 에러가 납니다. 
(사파리 , 크롬 둘다 테스트)
직업 document에 접근해서 생기는 문제 같은데 해결할 방법이 없을까요?

![image](https://user-images.githubusercontent.com/57941164/198763508-d9609e0b-6337-4615-befc-6adfb9235040.png)

다만,  콘솔에서 document.wrtie(sciprt)를  위의 embeded메소드에서 사용하는 것으로 보여지는데 ,이로 인해서 

Uncaught TypeError: Cannot read properties of null (reading 'document') 아래와 같은 에러가 콘솔에 뜹니다. 
작동상에는 문제가 없지만 에러가 뜨는 점이 좋진 않은데 ,직접 이 라이브러리 코드를 write를 안쓰고 read를 쓰는 쪽으로 해준다는지 해서 없애버리는 방법도 있을 것 같은데.. 

![image](https://user-images.githubusercontent.com/57941164/198762612-bb32a950-3d7a-41e9-856e-235eafe7c89f.png)

어떻게 해결 할 수 있을까요?

**Comment by Normaltic** [comment]
안녕하세요, 이슈 감사드립니다!

먼저, `react-daum-postcode`는 다음 우편번호 서비스를 감싸는 wrapper 역할만 하고 있으며, 해당 부분은 다음 우편번호 서비스 상의 코드 이기 때문에, 직접 수정은 힘듭니다.

그리고 해당 오류 메세지는 react@18 부터 development 환경에서 `React.StrictMode` 출력 되는걸로 파악하고 있는데, 개발 환경에서 document 가 없는 환경에서 해당 코드를 실행하며 발생하는게 아닐까 추측됩니다.

현재 wrapper 레벨에서 해결할 수 있는 부분이 있는지 고민하고 있는 상황입니다. 메세지는 production 환경이거나, 찝찝하지만 strict 모드를 끄면 출력을 회피할 수 있긴 합니다..

**Comment by april21dev** [comment]
같은 이슈입니다! 해결 기다리고 있겠습니다! 감사합니다~

**Comment by kdn00** [comment]
안녕하세요, 같은 이슈인데 해결됐을까요? 
![image](https://github.com/kmsbernard/react-daum-postcode/assets/89984853/5807fabd-6104-42ce-b03e-ac8d303d0226)

작동에는 문제가 없지만 react-daum-postcode를 사용한 컴포넌트를 호출할 때마다 아래처럼 떠서 해결하고 싶습니다
![image](https://github.com/kmsbernard/react-daum-postcode/assets/89984853/f6521ed2-f676-445a-8148-0dc4d72d177b)

**Comment by Normaltic** [comment]
안녕하세요! [3.1.3](https://github.com/kmsbernard/react-daum-postcode/releases/tag/v3.1.3) 릴리즈로, `react@18` 이상의 `StrictMode` 에서 더이상 오류 출력이 발생하지 않습니다. 확인 후 추가 문제가 있다면 이슈 부탁드립니다!

resolved #61
