### ISSUE TITLE
주소 선택 후 다시 주소를 검색할 시 창이 사라집니다

### ISSUE THREAD

**Issue by ojsung7** [kmsbernard/react-daum-postcode#59]
https://user-images.githubusercontent.com/30823778/212233044-b0dcacd9-7e56-4845-8142-45fc28036449.mp4

우이ㅘ 같이 주소선택 후 다시 검색을 하면 창이 사라지는 경우가 있습니다.

제가 잘못사용하고 있는건지 확인 좀 부탁드립니다...

```javascript
import React, { useEffect, useState } from "react";
import DaumPostcode from "react-daum-postcode";

const Daum__postcode = (props) => {

    const complete = (data) => {
        let fullAddress = data.address;
        let extraAddress = '';

        if (data.addressType === 'R') {
            if (data.bname !== '') {
                extraAddress += data.bname;
            }
            if (data.buildingName !== '') {
                extraAddress += (extraAddress !== '' ? `, ${data.buildingName}` : data.buildingName);
            }
            fullAddress += (extraAddress !== '' ? ` (${extraAddress})` : '');
        }
        console.log(data)
        console.log(fullAddress)
        console.log(data.zonecode)

        close_modal();
    }

    const close_modal = () => {
        document.getElementsByClassName('modal_container_wrap daum_post_code')[0].style.display = 'none'
    }

    return (
        <div className='modal_container_wrap daum_post_code'>
            <div className='company_modal_container flex_column'>
                <DaumPostcode className="postmodal" onComplete={complete} />
                <button onClick={() => close_modal()}>닫기</button>
            </div>
        </div>
    );
};

export default Daum__postcode;
```

**Comment by Normaltic** [comment]
안녕하세요, 이슈 감사드립니다!

해당 Modal은 DOM 에 한 번 마운트 되어 제거되지 않고, 열고 닫히는 동작을 css 로 핸들링 하는것으로 보입니다.

다음 우편번호 서비스에 `autoClose` 라는 옵션이 있는데, 주소 검색 및 선택을 완료하면 돔에서 제거되는 기능이며, `react-daum-postcode` 에서는 해당 옵션의 기본값을 `true` 로 전달하고 있습니다. 즉, `react-daum-postcode` 는 랜더링 될 때 다음 우편번호 서비스를 돔에 마운트 하며, 주소 선택 완료 시 다음 우편번호 서비스는 돔에서 제거됩니다.

따라서 위와 같이 구현하게 되면, 한 번 선택한 이후에는 우편번호 서비스가 돔에서 제거되어서, `display` 를 조작해도 검색창이 나타나지 않습니다. 그리고 `autoClose` 옵션을 `false` 로 준다면 다시 뜨겠지만, 위 구현에서는 선택 완료 후 다시 띄워도 검색 결과가 유지될 것으로 보입니다.

선택 결과를 유지하고 싶으시다면 `autoClose` 옵션을 `false` 로 전달하시고, 초기화를 하고 싶으시면 `display` 를 토글하는 대신 `DaumPostcode` 나 `Daum__postcode`( 해당 Modal ) 을  마운트-언마운트 시켜주는 로직으로 변경하시면 해결하실 수 있겠습니다!

**Comment by ojsung7** [comment]
답변갑사합니다!

```javascript
autoClose={false}
```

위와 같이 해결하였습니다.

**Comment by cksal0805** [comment]
해결 하셨다고 하니 다행인데, 
저는 검색 결과가 유지되면 안돼서, key값을 변경해서 리렌더링 시키도록 했습니다.

* Modal 은 antd modal 사용했습니다 :)
```js
<Modal
   title="주소검색"
  open={isModalOpened}
  onCancel={closeModal}
  footer={[]}
>
<DaumPostcodeEmbed
  key={isModalOpened ? "open" : "close"}
  onComplete={handleComplete}
/>
</Modal>

```
